#---------------------------1stian(naits)-------------
#----------------------------------------------
#--------------------SilkRoads-----------------
#-------------SilkRoads------------------------
#------SilkRoads-------------------------------
# Created by Stian "1stian" Tofte
# https://realnaits.com
# https://www.spigotmc.org/members/1stian.575219/

debug: false
settings:
  # What type of blocks you can place below your road.
  BlockBelowRoad:
    - "gravel"
    - "sponge"
  # What kind of blocks that are a valid road.
  RoadBlocks:
    - "stone"
    - "polished_andesite"
    - "polished_andesite_slab"
    - "smooth_stone_slab"
    - "stone_brick_slab"
    - "cobblestone_slab"
    - "granite_slab"
    - "polished_granite_slab"
    - "stone_slab"
  # Remove snow
  Snow: true
  # Stop starvation, while on valid roads. If sprinting starvation will still decrease.
  Starv: false
  # Increase walk speed.
  Walk:
    # Enable or disable.
    Enabled: true
    # Speed to choose. 0.2 is default walk speed. This wil also add some speed for running.
    Speed: 0.24